services:
  - type: web
    name: user-management-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: u875409848_igot
      - key: DB_PASSWORD
        value: 9T2Z5$3UKkgSYzE
      - key: DB_NAME
        value: u875409848_igot
      - key: JWT_SECRET
        value: mrbeans-secure-jwt-secret-key-2024
      - key: EMAIL_FROM
        value: mrbeans.dev@gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: mrbeans.dev@gmail.com
      - key: SMTP_PASS
        value: gezv stxl piar knuw
